services:
- type: web
  name: nome-do-seu-serviço
  repo: https://github.com/juliaNogueiraC/Aplica-o-Flask-Analise-de-dados-de-Demissoes-Departamento-Pessoal.git
  branch: main
  buildCommand: pip install -r requirements.txt
  startCommand: python app.py
  env:
    - key: FLASK_ENV
      value: production
